### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by paul-reiners** [cwoodall/pitch-shifter-py#9]
Hi,

I'm doing the following invocation:

`python ./bin/pitch-shifter.py -s ./samples/0a7c2a8d_nohash_0.wav -o out.wav -c 4096 -e .9 -p -7 -b .8
`
I would attach the 0a7c2a8d_nohash_0.wav file mentioned, but .wav file types are not supported.  However, you can get it [here](https://www.dropbox.com/s/emp3v75lbm733e8/0a7c2a8d_nohash_0.wav?dl=0).

When I run it the command, I get the following error:

```
Namespace(blend=0.8, chunk_size=4096, debug=False, no_resample=False, out='out.wav', overlap=0.9, pitch=-7.0, source='./samples/0a7c2a8d_nohash_0.wav')
Traceback (most recent call last):
  File "./bin/pitch-shifter.py", line 73, in <module>
    main(args)
  File "./bin/pitch-shifter.py", line 37, in main
    mono_samples = ps.stereoToMono(audio_samples)
  File "/Users/paulreiners/Dropbox/projects/pitch-shifter-py/pitchshifter/utilities.py", line 44, in stereoToMono
    [(sample[RIGHT] + sample[LEFT])/2 for sample in audio_samples], 
TypeError: 'int' object has no attribute '__getitem__'
```
Any idea what I'm doing wrong here?  The command works fine with the sample file, sample1.wav.

**Comment by cwoodall** [comment]
Hey! is there any chance your wav is mono? I assume a stereo input and then convert it to mono because otherwise it becomes hard to run. This should be handled differently most likely

**Comment by cwoodall** [comment]
Hey I should have fixed this in the latest updates and I also added some additional examples. Actually committed the requirements.txt file. etc

**Comment by cwoodall** [comment]
Also I tested it against your file. Also since your sample is so short I think reducing the chunk size and playing with the overlap will help you get better sounds. Increasing the chunk size helps for songs/things with more movement but due to the nature of the algorithm tends to introduce a tad of delay and can smear or cause artifacts. However, the farther away the transform is the larger this needs to be and the overlap needs to be adjusted appropriately to reduce the artifacts. I have not sorted out all of the math to make this easy, but you should be able to tweak it by playing with -e and -c
